server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  elasticsearch:
    rest:
      uris: 192.168.118.128:9200
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
  rabbitmq:
    port: 5672
    host: 192.168.118.128
    virtual-host: /gouge
    password: gouge
    username: gouge
    listener:
      simple:
        concurrency: 4
        prefetch: 1
        acknowledge-mode: manual
feign:
  sentinel:
    enabled: true
